package com.vcortes.canjehoras.model;

// Generated 31-ene-2015 17:30:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Agenda generated by hbm2java
 */
public class Agenda implements java.io.Serializable {

	private Integer id;
	private Trueque trueque;
	private Date fecha;
	private String horaInicio;
	private String horaFin;
	private Boolean estado;

	public Agenda() {
	}

	public Agenda(Trueque trueque, Date fecha, String horaInicio, String horaFin) {
		this.trueque = trueque;
		this.fecha = fecha;
		this.horaInicio = horaInicio;
		this.horaFin = horaFin;
	}

	public Agenda(Trueque trueque, Date fecha, String horaInicio,
			String horaFin, Boolean estado) {
		this.trueque = trueque;
		this.fecha = fecha;
		this.horaInicio = horaInicio;
		this.horaFin = horaFin;
		this.estado = estado;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Trueque getTrueque() {
		return this.trueque;
	}

	public void setTrueque(Trueque trueque) {
		this.trueque = trueque;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(String horaInicio) {
		this.horaInicio = horaInicio;
	}

	public String getHoraFin() {
		return this.horaFin;
	}

	public void setHoraFin(String horaFin) {
		this.horaFin = horaFin;
	}

	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

}
