package com.vcortes.canjehoras.model;

// Generated 31-ene-2015 17:30:18 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria implements java.io.Serializable {

	private Integer id;
	private String codigo;
	private String descripcion;
	private Set trueques = new HashSet(0);
	private Set preferenciases = new HashSet(0);

	public Categoria() {
	}

	public Categoria(String codigo, String descripcion) {
		this.codigo = codigo;
		this.descripcion = descripcion;
	}

	public Categoria(String codigo, String descripcion, Set trueques,
			Set preferenciases) {
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.trueques = trueques;
		this.preferenciases = preferenciases;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getTrueques() {
		return this.trueques;
	}

	public void setTrueques(Set trueques) {
		this.trueques = trueques;
	}

	public Set getPreferenciases() {
		return this.preferenciases;
	}

	public void setPreferenciases(Set preferenciases) {
		this.preferenciases = preferenciases;
	}

}
