package com.vcortes.canjehoras.model;

// Generated 31-ene-2015 17:30:18 by Hibernate Tools 3.4.0.CR1

/**
 * Preferencias generated by hbm2java
 */
public class Preferencias implements java.io.Serializable {

	private Integer id;
	private Usuario usuario;
	private Categoria categoria;
	private Provincia provincia;

	public Preferencias() {
	}

	public Preferencias(Usuario usuario, Categoria categoria,
			Provincia provincia) {
		this.usuario = usuario;
		this.categoria = categoria;
		this.provincia = provincia;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public Provincia getProvincia() {
		return this.provincia;
	}

	public void setProvincia(Provincia provincia) {
		this.provincia = provincia;
	}

}
