package com.vcortes.canjehoras.model;
// Generated 31-ene-2015 11:15:40 by Hibernate Tools 3.4.0.CR1

import java.util.Set;


/**
 * Provincia generated by hbm2java
 */
public class Provincia implements java.io.Serializable {

	private Integer id;
	private String codigo;
	private String descripcion;
//	private Set usuarios = new HashSet(0);
//	private Set preferenciases = new HashSet(0);

	public Provincia() {
	}

	public Provincia(String codigo, String descripcion) {
		this.codigo = codigo;
		this.descripcion = descripcion;
	}

	public Provincia(String codigo, String descripcion, Set usuarios,
			Set preferenciases) {
		this.codigo = codigo;
		this.descripcion = descripcion;
//		this.usuarios = usuarios;
//		this.preferenciases = preferenciases;
	}
	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

//	public Set getUsuarios() {
//		return this.usuarios;
//	}
//
//	public void setUsuarios(Set usuarios) {
//		this.usuarios = usuarios;
//	}
//
//	public Set getPreferenciases() {
//		return this.preferenciases;
//	}
//
//	public void setPreferenciases(Set preferenciases) {
//		this.preferenciases = preferenciases;
//	}

}
