package com.vcortes.canjehoras.model;

// Generated 31-ene-2015 17:30:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Trueque generated by hbm2java
 */
public class Trueque implements java.io.Serializable {

	private Integer id;
	private Usuario usuario;
	private Categoria categoria;
	private Estado estado;
	private Date fechaAlta;
	private String titulo;
	private String descripcion;
	private String tipo;
	private byte[] imagen;
	private Set agendas = new HashSet(0);

	public Trueque() {
	}

	public Trueque(Usuario usuario, Categoria categoria, Estado estado,
			Date fechaAlta, String titulo, String descripcion) {
		this.usuario = usuario;
		this.categoria = categoria;
		this.estado = estado;
		this.fechaAlta = fechaAlta;
		this.titulo = titulo;
		this.descripcion = descripcion;
	}

	public Trueque(Usuario usuario, Categoria categoria, Estado estado,
			Date fechaAlta, String titulo, String descripcion, String tipo,
			byte[] imagen, Set agendas) {
		this.usuario = usuario;
		this.categoria = categoria;
		this.estado = estado;
		this.fechaAlta = fechaAlta;
		this.titulo = titulo;
		this.descripcion = descripcion;
		this.tipo = tipo;
		this.imagen = imagen;
		this.agendas = agendas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public byte[] getImagen() {
		return this.imagen;
	}

	public void setImagen(byte[] imagen) {
		this.imagen = imagen;
	}

	public Set getAgendas() {
		return this.agendas;
	}

	public void setAgendas(Set agendas) {
		this.agendas = agendas;
	}

}
