package com.vcortes.canjehoras.model;

// Generated 31-ene-2015 17:30:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private Integer id;
	private Idioma idioma;
	private Provincia provincia;
	private Perfil perfil;
	private String correoElectronico;
	private String pass;
	private Boolean estado;
	private Date fechaAlta;
	private Date fechaBaja;
	private String apellido1;
	private String apellido2;
	private String nombre;
	private String movil;
	private String telefono;
	private Boolean wassap;
	private Integer numAcceso;
	private Date fechaUltimoAcceso;
	private Set trueques = new HashSet(0);
	private Set preferenciases = new HashSet(0);

	public Usuario() {
	}

	public Usuario(Idioma idioma, Perfil perfil, String correoElectronico,
			String pass, Date fechaAlta, String nombre, String movil) {
		this.idioma = idioma;
		this.perfil = perfil;
		this.correoElectronico = correoElectronico;
		this.pass = pass;
		this.fechaAlta = fechaAlta;
		this.nombre = nombre;
		this.movil = movil;
	}

	public Usuario(Idioma idioma, Provincia provincia, Perfil perfil,
			String correoElectronico, String pass, Boolean estado,
			Date fechaAlta, Date fechaBaja, String apellido1, String apellido2,
			String nombre, String movil, String telefono, Boolean wassap,
			Integer numAcceso, Date fechaUltimoAcceso, Set trueques,
			Set preferenciases) {
		this.idioma = idioma;
		this.provincia = provincia;
		this.perfil = perfil;
		this.correoElectronico = correoElectronico;
		this.pass = pass;
		this.estado = estado;
		this.fechaAlta = fechaAlta;
		this.fechaBaja = fechaBaja;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.nombre = nombre;
		this.movil = movil;
		this.telefono = telefono;
		this.wassap = wassap;
		this.numAcceso = numAcceso;
		this.fechaUltimoAcceso = fechaUltimoAcceso;
		this.trueques = trueques;
		this.preferenciases = preferenciases;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Idioma getIdioma() {
		return this.idioma;
	}

	public void setIdioma(Idioma idioma) {
		this.idioma = idioma;
	}

	public Provincia getProvincia() {
		return this.provincia;
	}

	public void setProvincia(Provincia provincia) {
		this.provincia = provincia;
	}

	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	public String getCorreoElectronico() {
		return this.correoElectronico;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getMovil() {
		return this.movil;
	}

	public void setMovil(String movil) {
		this.movil = movil;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public Boolean getWassap() {
		return this.wassap;
	}

	public void setWassap(Boolean wassap) {
		this.wassap = wassap;
	}

	public Integer getNumAcceso() {
		return this.numAcceso;
	}

	public void setNumAcceso(Integer numAcceso) {
		this.numAcceso = numAcceso;
	}

	public Date getFechaUltimoAcceso() {
		return this.fechaUltimoAcceso;
	}

	public void setFechaUltimoAcceso(Date fechaUltimoAcceso) {
		this.fechaUltimoAcceso = fechaUltimoAcceso;
	}

	public Set getTrueques() {
		return this.trueques;
	}

	public void setTrueques(Set trueques) {
		this.trueques = trueques;
	}

	public Set getPreferenciases() {
		return this.preferenciases;
	}

	public void setPreferenciases(Set preferenciases) {
		this.preferenciases = preferenciases;
	}

}
