CREATE TABLE PROVINCIA (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	CODIGO VARCHAR(20) NOT NULL,
	DESCRIPCION VARCHAR(50) NOT NULL, 
	PRIMARY KEY (ID),
	UNIQUE (CODIGO),
	INDEX (CODIGO)
) ENGINE=InnoDB /*!40100 DEFAULT CHARSET utf8 COLLATE utf8_bin */;

INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('A CORUÑA', 'A CORUÑA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ALAVA', 'ALAVA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ALBACETE', 'ALBACETE');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ALICANTE', 'ALICANTE');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ALMERIA', 'ALMERIA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ASTURIAS', 'ASTURIAS');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('AVILA', 'AVILA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('BADAJOZ', 'BADAJOZ');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('BARCELONA', 'BARCELONA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('BURGOS', 'BURGOS');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('CACERES', 'CACERES');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('CADIZ', 'CADIZ');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('CANTABRIA', 'CANTABRIA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('CASTELLON', 'CASTELLON');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('CEUTA', 'CEUTA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('CIUDAD REAL', 'CIUDAD REAL');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('CORDOBA', 'CORDOBA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('CUENCA', 'CUENCA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('GIRONA', 'GIRONA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('GRANADA', 'GRANADA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('GUADALAJARA', 'GUADALAJARA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('GUIPUZCOA', 'GUIPUZCOA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('HUELVA', 'HUELVA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('HUESCA', 'HUESCA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ILLES BALEARS', 'ILLES BALEARS');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('JAEN', 'JAEN');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('LA RIOJA', 'LA RIOJA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('LAS PALMAS', 'LAS PALMAS');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('LEON', 'LEON');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('LLEIDA', 'LLEIDA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('LUGO', 'LUGO');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('MADRID', 'MADRID');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('MALAGA', 'MALAGA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('MELILLA', 'MELILLA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('MURCIA', 'MURCIA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('NAVARRA', 'NAVARRA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('OURENSE', 'OURENSE');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('PALENCIA', 'PALENCIA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('PONTEVEDRA', 'PONTEVEDRA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('SALAMANCA', 'SALAMANCA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('TENERIFE', 'SANTA CRUZ DE TENERIFE');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('SEGOVIA', 'SEGOVIA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('SEVILLA', 'SEVILLA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('SORIA', 'SORIA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('TARRAGONA', 'TARRAGONA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('TERUEL', 'TERUEL');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('TOLEDO', 'TOLEDO');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('VALENCIA', 'VALENCIA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('VALLADOLID', 'VALLADOLID');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('VIZCAYA', 'VIZCAYA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ZAMORA', 'ZAMORA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ZARAGOZA', 'ZARAGOZA');

CREATE TABLE PERFIL (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	CODIGO VARCHAR(3) NOT NULL,
	DESCRIPCION VARCHAR(50) NOT NULL, 
	PRIMARY KEY (ID),
	UNIQUE (CODIGO),
	INDEX (CODIGO)
) ENGINE=InnoDB /*!40100 DEFAULT CHARSET utf8 COLLATE utf8_bin */;

INSERT INTO PERFIL (CODIGO, DESCRIPCION) VALUES ('A', 'Administrador');
INSERT INTO PERFIL (CODIGO, DESCRIPCION) VALUES ('U', 'Usuario');

CREATE TABLE IDIOMA (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	CODIGO VARCHAR(20) NOT NULL,
	DESCRIPCION VARCHAR(50) NOT NULL, 
	PRIMARY KEY (ID),
	UNIQUE (CODIGO),
	INDEX (CODIGO)
) ENGINE=InnoDB /*!40100 DEFAULT CHARSET utf8 COLLATE utf8_bin */;

INSERT INTO IDIOMA (CODIGO, DESCRIPCION) VALUES ('ES', 'Español');
INSERT INTO IDIOMA (CODIGO, DESCRIPCION) VALUES ('EU', 'Ingles');

CREATE TABLE CATEGORIA (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	CODIGO VARCHAR(20) NOT NULL,
	DESCRIPCION VARCHAR(50) NOT NULL, 
	PRIMARY KEY (ID),
	UNIQUE (CODIGO),
	INDEX (CODIGO)
) ENGINE=InnoDB /*!40100 DEFAULT CHARSET utf8 COLLATE utf8_bin */;

INSERT INTO CATEGORIA (CODIGO, DESCRIPCION) VALUES ('INFORMATICA', 'INFORMATICA');
INSERT INTO CATEGORIA (CODIGO, DESCRIPCION) VALUES ('IDIOMAS', 'IDIOMAS');
INSERT INTO CATEGORIA (CODIGO, DESCRIPCION) VALUES ('DEPORTE', 'DEPORTE');

CREATE TABLE ESTADO (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	CODIGO VARCHAR(10) NOT NULL,
	DESCRIPCION VARCHAR(50) NOT NULL, 
	PRIMARY KEY (ID),
	UNIQUE (CODIGO),
	INDEX (CODIGO)
) ENGINE=InnoDB /*!40100 DEFAULT CHARSET utf8 COLLATE utf8_bin */;

INSERT INTO ESTADO (CODIGO, DESCRIPCION) VALUES ('ABI', 'ABIERTO');
INSERT INTO ESTADO (CODIGO, DESCRIPCION) VALUES ('PROC', 'EN PROCESO');
INSERT INTO ESTADO (CODIGO, DESCRIPCION) VALUES ('CER', 'CERRADO');
INSERT INTO ESTADO (CODIGO, DESCRIPCION) VALUES ('DEN', 'DENUNCIADO');
INSERT INTO ESTADO (CODIGO, DESCRIPCION) VALUES ('BOR', 'BORRADO');
INSERT INTO ESTADO (CODIGO, DESCRIPCION) VALUES ('CAD', 'CADUCADO');

