CREATE TABLE USUARIO (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	ID_PERFIL INT NOT NULL,
	CORREO_ELECTRONICO VARCHAR(50) NOT NULL,
	PASS VARCHAR(20) NOT NULL,
	ESTADO TINYINT(1) UNSIGNED DEFAULT '1' NULL COMMENT '1-ACTIVO / 0-BAJA',
	FECHA_ALTA TIMESTAMP NOT NULL,
	FECHA_BAJA TIMESTAMP NULL DEFAULT NULL,
	APELLIDO1 VARCHAR(25),
	APELLIDO2 VARCHAR(25),
	NOMBRE VARCHAR(20) NOT NULL,
	ID_PROVINCIA INT,
	MOVIL VARCHAR(15) NOT NULL,
	TELEFONO VARCHAR(15),
	WASSAP TINYINT(1) UNSIGNED DEFAULT '0' NULL COMMENT '1-SI / 0-NO',
	ID_IDIOMA INT NOT NULL DEFAULT '1',
	NUM_ACCESO INT,
	FECHA_ULTIMO_ACCESO TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_PERFIL) REFERENCES PERFIL(ID),
	FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA(ID),
	FOREIGN KEY (ID_IDIOMA) REFERENCES IDIOMA(ID)
) ENGINE=InnoDB /*!40100 DEFAULT CHARSET utf8 COLLATE utf8_bin */;

INSERT INTO USUARIO (ID_PERFIL, CORREO_ELECTRONICO, PASS, FECHA_ALTA, NOMBRE, MOVIL, WASSAP) VALUES (1, 'canjehoras@gmail.com', 'root',  '2015/01/25', 'Administrador', '652434891', 1);

CREATE TABLE PREFERENCIAS(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	ID_USUARIO INT NOT NULL,
	ID_PROVINCIA INT NOT NULL,
	ID_CATEGORIA INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
	FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA(ID),
	FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID)
) ENGINE=InnoDB /*!40100 DEFAULT CHARSET utf8 COLLATE utf8_bin */;


CREATE TABLE TRUEQUE(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	ID_USUARIO INT NOT NULL,
	FECHA_ALTA TIMESTAMP NOT NULL,
	ID_CATEGORIA INT NOT NULL,
	ID_ESTADO INT NOT NULL,
	TITULO VARCHAR(50) NOT NULL,
	DESCRIPCION VARCHAR(500) NOT NULL,
	TIPO VARCHAR(1),
	IMAGEN BLOB,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
	FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID),
	FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID)
) ENGINE=InnoDB /*!40100 DEFAULT CHARSET utf8 COLLATE utf8_bin */;


CREATE TABLE AGENDA(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	FECHA TIMESTAMP NOT NULL,
	HORA_INICIO VARCHAR(5) NOT NULL,
	HORA_FIN VARCHAR(5) NOT NULL,
	ESTADO TINYINT(1) UNSIGNED DEFAULT '1' NULL COMMENT '1-DISPONIBLE / 0-NO DISPONIBLE',
	ID_TRUEQUE INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_TRUEQUE) REFERENCES TRUEQUE(ID)
) ENGINE=InnoDB /*!40100 DEFAULT CHARSET utf8 COLLATE utf8_bin */;
