-- CREAR DATABASE --
DROP DATABASE IF EXISTS canjehoras;
CREATE DATABASE canjehoras /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_bin */;
use canjehoras;

-- TABLA PROVINCIA --
CREATE TABLE PROVINCIA (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	CODIGO VARCHAR(10) NOT NULL,
	DESCRIPCION VARCHAR(50) NOT NULL, 
	PRIMARY KEY (ID),
	UNIQUE (DESCRIPCION),
	INDEX (DESCRIPCION)
) ENGINE=InnoDB /*!40100 DEFAULT CHARSET utf8 COLLATE utf8_bin */;

-- DATOS POR DEFECTO -- TABLA PROVINCIA --
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-C', 'A CORUÑA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-VI', 'ALAVA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-AB', 'ALBACETE');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-A', 'ALICANTE');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-AL', 'ALMERIA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-O', 'ASTURIAS');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-AV', 'AVILA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-BA', 'BADAJOZ');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-B', 'BARCELONA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-BU', 'BURGOS');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-CC', 'CACERES');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-CA', 'CADIZ');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-S', 'CANTABRIA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-CS', 'CASTELLON');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-CE', 'CEUTA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-CR', 'CIUDAD REAL');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-CO', 'CORDOBA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-CU', 'CUENCA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-GI', 'GIRONA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-GR', 'GRANADA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-GU', 'GUADALAJARA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-SS', 'GUIPUZCOA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-H', 'HUELVA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-HU', 'HUESCA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-PB', 'ISLAS BALEARES');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-J', 'JAEN');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-LO', 'LA RIOJA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-GC', 'LAS PALMAS');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-LE', 'LEON');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-L', 'LLEIDA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-LU', 'LUGO');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-M', 'MADRID');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-MA', 'MALAGA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-ML', 'MELILLA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-MU', 'MURCIA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-NA', 'NAVARRA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-OR', 'OURENSE');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-P', 'PALENCIA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-PO', 'PONTEVEDRA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-SA', 'SALAMANCA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-T', 'SANTA CRUZ DE TENERIFE');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-SG', 'SEGOVIA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-SE', 'SEVILLA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-SO', 'SORIA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-T', 'TARRAGONA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-TE', 'TERUEL');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-TO', 'TOLEDO');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-V', 'VALENCIA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-VA', 'VALLADOLID');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-VI', 'VIZCAYA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-ZA', 'ZAMORA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES-Z', 'ZARAGOZA');

-- TABLA CATEGORIA --
CREATE TABLE CATEGORIA (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	DESCRIPCION VARCHAR(50) NOT NULL, 
	PRIMARY KEY (ID),
	UNIQUE (DESCRIPCION),
	INDEX (DESCRIPCION)
) ENGINE=InnoDB /*!40100 DEFAULT CHARSET utf8 COLLATE utf8_bin */;

-- DATOS POR DEFECTO -- TABLA CATEGORIA --
INSERT INTO CATEGORIA(DESCRIPCION) VALUES ('OCIO');
INSERT INTO CATEGORIA(DESCRIPCION) VALUES ('BRICOLAJE');
INSERT INTO CATEGORIA(DESCRIPCION) VALUES ('ALIMENTACIÓN');
INSERT INTO CATEGORIA(DESCRIPCION) VALUES ('MOTOR');
INSERT INTO CATEGORIA(DESCRIPCION) VALUES ('JUGUETES');
INSERT INTO CATEGORIA(DESCRIPCION) VALUES ('NIÑOS');
INSERT INTO CATEGORIA(DESCRIPCION) VALUES ('INFORMÁTICA');
INSERT INTO CATEGORIA(DESCRIPCION) VALUES ('COLECCIONES');
INSERT INTO CATEGORIA(DESCRIPCION) VALUES ('DEPORTE');
INSERT INTO CATEGORIA(DESCRIPCION) VALUES ('ARTE');
INSERT INTO CATEGORIA(DESCRIPCION) VALUES ('LIBROS');
INSERT INTO CATEGORIA(DESCRIPCION) VALUES ('BELLEZA');
INSERT INTO CATEGORIA(DESCRIPCION) VALUES ('MODA');
INSERT INTO CATEGORIA(DESCRIPCION) VALUES ('OTROS');

-- TABLA USUARIO --
CREATE TABLE USUARIO (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	IDIOMA VARCHAR(2) NOT NULL,
	PERFIL VARCHAR(2) NOT NULL,
	FECHA_ALTA DATE NOT NULL,
	FECHA_BAJA DATE NULL DEFAULT NULL,
	CORREO_ELECTRONICO VARCHAR(50) NOT NULL,
	PASS VARCHAR(20) NOT NULL,	
	NOMBRE VARCHAR(20) NOT NULL,
	APELLIDO1 VARCHAR(25) NOT NULL,
	APELLIDO2 VARCHAR(25),
	ID_PROVINCIA INT,
	MOVIL VARCHAR(15) NOT NULL,
	TELEFONO VARCHAR(15),
	WASSAP TINYINT(1) UNSIGNED DEFAULT '0' NULL COMMENT '1-SI / 0-NO',
	NUM_ACCESO INT,
	FECHA_ULTIMO_ACCESO DATE NULL DEFAULT NULL, 
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA(ID)
) ENGINE=InnoDB /*!40100 DEFAULT CHARSET utf8 COLLATE utf8_bin */;

-- DATOS POR DEFECTO -- TABLA USUARIO --
INSERT INTO USUARIO (IDIOMA, PERFIL, FECHA_ALTA, CORREO_ELECTRONICO, PASS, NOMBRE, APELLIDO1, ID_PROVINCIA, MOVIL) VALUES ('ES', 'A', '2015/01/25', 'canjehoras@gmail.com', 'root', 'Administrador', 'Usuario', 52, '652434891');

-- TABLA PREF_PROVINCIA --
CREATE TABLE PREF_PROVINCIA(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	ID_USUARIO INT NOT NULL,
	ID_PROVINCIA INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
	FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA(ID)
) ENGINE=InnoDB /*!40100 DEFAULT CHARSET utf8 COLLATE utf8_bin */;

-- TABLA PREF_CATEGORIA --
CREATE TABLE PREF_CATEGORIA(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	ID_USUARIO INT NOT NULL,
	ID_CATEGORIA INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
	FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID)
) ENGINE=InnoDB /*!40100 DEFAULT CHARSET utf8 COLLATE utf8_bin */;

-- TABLA TRUEQUE --
CREATE TABLE TRUEQUE(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	ID_USUARIO INT NOT NULL,
	ID_PROVINCIA INT NOT NULL,
	FECHA_ALTA DATE NOT NULL,
	ID_CATEGORIA INT NOT NULL,
	ESTADO VARCHAR(1) NOT NULL,
	TITULO VARCHAR(50) NOT NULL,
	DESCRIPCION VARCHAR(500) NOT NULL,
	TIPO VARCHAR(1),
	IMAGEN LONGBLOB,
	MODALIDAD VARCHAR(1),
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
	FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA(ID),
	FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID)
) ENGINE=InnoDB /*!40100 DEFAULT CHARSET utf8 COLLATE utf8_bin */;

-- TABLA AGENDA --
CREATE TABLE AGENDA(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	ID_USUARIO INT NOT NULL,
	ESTADO TINYINT(1) UNSIGNED DEFAULT '1' NULL COMMENT '1-DISPONIBLE / 0-NO DISPONIBLE',
	PRIMARY KEY (ID), 
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
) ENGINE=InnoDB /*!40100 DEFAULT CHARSET utf8 COLLATE utf8_bin */;

-- TABLA CANJE --
CREATE TABLE CANJE(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	ID_USUARIO INT NOT NULL,
	ID_TRUEQUE INT NOT NULL,
	ID_AGENDA INT NOT NULL,
	FECHA DATE NOT NULL,
	HORA_INICIO VARCHAR(5) NOT NULL,
	HORA_FIN VARCHAR(5) NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
	FOREIGN KEY (ID_TRUEQUE) REFERENCES TRUEQUE(ID),
	FOREIGN KEY (ID_AGENDA) REFERENCES AGENDA(ID)
) ENGINE=InnoDB /*!40100 DEFAULT CHARSET utf8 COLLATE utf8_bin */;

-- TABLA FORO --
CREATE TABLE FORO(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	ID_TRUEQUE INT NOT NULL,
	FECHA_CREACION DATE NOT NULL,
	HORA_CREACION VARCHAR(5) NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_TRUEQUE) REFERENCES TRUEQUE(ID)
) ENGINE=InnoDB /*!40100 DEFAULT CHARSET utf8 COLLATE utf8_bin */;

-- TABLA PUBLICACION --
CREATE TABLE PUBLICACION(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	ID_USUARIO INT NOT NULL,
	ID_FORO INT NOT NULL,
	FECHA DATE NOT NULL,
	HORA VARCHAR(5) NOT NULL,
	COMENTARIO VARCHAR(500) NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
	FOREIGN KEY (ID_FORO) REFERENCES FORO(ID)
) ENGINE=InnoDB /*!40100 DEFAULT CHARSET utf8 COLLATE utf8_bin */;