-- CREAR DATABASE --
DROP DATABASE IF EXISTS canjehoras;
CREATE DATABASE canjehoras /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_bin */;
use canjehoras;

-- TABLA PROVINCIA --
CREATE TABLE PROVINCIA (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	CODIGO VARCHAR(10) NOT NULL,
	DESCRIPCION VARCHAR(50) NOT NULL, 
	PRIMARY KEY (ID),
	UNIQUE (DESCRIPCION),
	INDEX (DESCRIPCION)
) ENGINE=InnoDB /*!40100 DEFAULT CHARSET utf8 COLLATE utf8_bin */;

-- DATOS POR DEFECTO -- TABLA PROVINCIA --
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_C', 'A CORUÑA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_VI', 'ALAVA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_AB', 'ALBACETE');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_A', 'ALICANTE');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_AL', 'ALMERIA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_O', 'ASTURIAS');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_AV', 'AVILA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_BA', 'BADAJOZ');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_B', 'BARCELONA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_BU', 'BURGOS');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_CC', 'CACERES');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_CA', 'CADIZ');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_S', 'CANTABRIA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_CS', 'CASTELLON');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_CE', 'CEUTA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_CR', 'CIUDAD REAL');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_CO', 'CORDOBA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_CU', 'CUENCA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_GI', 'GIRONA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_GR', 'GRANADA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_GU', 'GUADALAJARA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_SS', 'GUIPUZCOA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_H', 'HUELVA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_HU', 'HUESCA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_PB', 'ISLAS BALEARES');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_J', 'JAEN');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_LO', 'LA RIOJA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_GC', 'LAS PALMAS');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_LE', 'LEON');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_L', 'LLEIDA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_LU', 'LUGO');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_M', 'MADRID');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_MA', 'MALAGA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_ML', 'MELILLA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_MU', 'MURCIA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_NA', 'NAVARRA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_OR', 'OURENSE');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_P', 'PALENCIA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_PO', 'PONTEVEDRA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_SA', 'SALAMANCA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_T', 'SANTA CRUZ DE TENERIFE');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_SG', 'SEGOVIA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_SE', 'SEVILLA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_SO', 'SORIA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_T', 'TARRAGONA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_TE', 'TERUEL');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_TO', 'TOLEDO');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_V', 'VALENCIA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_VA', 'VALLADOLID');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_VI', 'VIZCAYA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_ZA', 'ZAMORA');
INSERT INTO PROVINCIA(CODIGO, DESCRIPCION) VALUES ('ES_Z', 'ZARAGOZA');

-- TABLA CATEGORIA --
CREATE TABLE CATEGORIA (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	DESCRIPCION VARCHAR(50) NOT NULL, 
	PRIMARY KEY (ID),
	UNIQUE (DESCRIPCION),
	INDEX (DESCRIPCION)
) ENGINE=InnoDB /*!40100 DEFAULT CHARSET utf8 COLLATE utf8_bin */;

-- DATOS POR DEFECTO -- TABLA CATEGORIA --
INSERT INTO CATEGORIA(DESCRIPCION) VALUES ('OCIO');
INSERT INTO CATEGORIA(DESCRIPCION) VALUES ('BRICOLAJE');
INSERT INTO CATEGORIA(DESCRIPCION) VALUES ('ALIMENTACIÓN');
INSERT INTO CATEGORIA(DESCRIPCION) VALUES ('MOTOR');
INSERT INTO CATEGORIA(DESCRIPCION) VALUES ('JUGUETES');
INSERT INTO CATEGORIA(DESCRIPCION) VALUES ('NIÑOS');
INSERT INTO CATEGORIA(DESCRIPCION) VALUES ('INFORMÁTICA');
INSERT INTO CATEGORIA(DESCRIPCION) VALUES ('COLECCIONES');
INSERT INTO CATEGORIA(DESCRIPCION) VALUES ('DEPORTE');
INSERT INTO CATEGORIA(DESCRIPCION) VALUES ('ARTE');
INSERT INTO CATEGORIA(DESCRIPCION) VALUES ('LIBROS');
INSERT INTO CATEGORIA(DESCRIPCION) VALUES ('BELLEZA');
INSERT INTO CATEGORIA(DESCRIPCION) VALUES ('MODA');
INSERT INTO CATEGORIA(DESCRIPCION) VALUES ('OTROS');

-- TABLA AGENDA --
CREATE TABLE AGENDA(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	ESTADO TINYINT(1) UNSIGNED DEFAULT '1' NULL COMMENT '1-DISPONIBLE / 0-NO DISPONIBLE',
	PRIMARY KEY (ID)
) ENGINE=InnoDB /*!40100 DEFAULT CHARSET utf8 COLLATE utf8_bin */;

-- TABLA USUARIO --
CREATE TABLE USUARIO (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	IDIOMA VARCHAR(2) NOT NULL,
	PERFIL VARCHAR(2) NOT NULL,
	FECHA_ALTA DATE NOT NULL,
	FECHA_BAJA DATE NULL DEFAULT NULL,
	CORREO_ELECTRONICO VARCHAR(50) NOT NULL,
	PASS VARCHAR(20) NOT NULL,	
	NOMBRE VARCHAR(20) NOT NULL,
	APELLIDO1 VARCHAR(25) NOT NULL,
	APELLIDO2 VARCHAR(25),
	ID_PROVINCIA INT,
	MOVIL VARCHAR(15) NOT NULL,
	TELEFONO VARCHAR(15),
	WASSAP TINYINT(1) UNSIGNED DEFAULT '0' NULL COMMENT '1-SI / 0-NO',
	NUM_ACCESO INT,
	FECHA_ULTIMO_ACCESO DATE NULL DEFAULT NULL,
	ID_AGENDA INT,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA(ID),
	FOREIGN KEY (ID_AGENDA) REFERENCES AGENDA(ID)
) ENGINE=InnoDB /*!40100 DEFAULT CHARSET utf8 COLLATE utf8_bin */;

-- DATOS POR DEFECTO -- TABLA USUARIO --
INSERT INTO USUARIO (IDIOMA, PERFIL, FECHA_ALTA, CORREO_ELECTRONICO, PASS, NOMBRE, APELLIDO1, ID_PROVINCIA, MOVIL) VALUES ('ES', 'A', '2015/01/25', 'canjehoras@gmail.com', 'root', 'Administrador', 'Usuario', 52, '652434891');

-- TABLA PREF_PROVINCIA --
CREATE TABLE PREF_PROVINCIA(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	ID_USUARIO INT NOT NULL,
	ID_PROVINCIA INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
	FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA(ID)
) ENGINE=InnoDB /*!40100 DEFAULT CHARSET utf8 COLLATE utf8_bin */;

-- TABLA PREF_CATEGORIA --
CREATE TABLE PREF_CATEGORIA(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	ID_USUARIO INT NOT NULL,
	ID_CATEGORIA INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
	FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID)
) ENGINE=InnoDB /*!40100 DEFAULT CHARSET utf8 COLLATE utf8_bin */;

-- TABLA TRUEQUE --
CREATE TABLE TRUEQUE(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	ID_USUARIO INT NOT NULL,
	ID_PROVINCIA INT NOT NULL,
	FECHA_ALTA DATE NOT NULL,
	ID_CATEGORIA INT NOT NULL,
	ESTADO VARCHAR(1) NOT NULL,
	TITULO VARCHAR(50) NOT NULL,
	DESCRIPCION VARCHAR(500) NOT NULL,
	TIPO VARCHAR(1),
	IMAGEN LONGBLOB,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
	FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA(ID),
	FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID)
) ENGINE=InnoDB /*!40100 DEFAULT CHARSET utf8 COLLATE utf8_bin */;

-- TABLA CANJE --
CREATE TABLE CANJE(
	ID_USUARIO INT NOT NULL,
	ID_TRUEQUE INT NOT NULL,
	ID_AGENDA INT NOT NULL,
	FECHA DATE NOT NULL,
	HORA_INICIO VARCHAR(5) NOT NULL,
	HORA_FIN VARCHAR(5) NOT NULL,
	PRIMARY KEY (ID_USUARIO, ID_AGENDA, ID_TRUEQUE),
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
	FOREIGN KEY (ID_TRUEQUE) REFERENCES TRUEQUE(ID),
	FOREIGN KEY (ID_AGENDA) REFERENCES AGENDA(ID)
) ENGINE=InnoDB /*!40100 DEFAULT CHARSET utf8 COLLATE utf8_bin */;